# Generated by Django 3.2.25 on 2025-01-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrel',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('barrel_shape', models.CharField(choices=[('Straight', 'Straight'), ('Tapered', 'Tapered')], max_length=255)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('shape', models.CharField(choices=[('Standard', 'Standard'), ('Kite', 'Kite')], max_length=255)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('length', models.CharField(choices=[('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], max_length=255)),
            ],
            bases=('products.product',),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
