# Generated by Django 3.2.25 on 2025-01-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='shape',
            new_name='flight_shape',
        ),
        migrations.RenameField(
            model_name='stem',
            old_name='length',
            new_name='stem_length',
        ),
    ]
