# Generated by Django 3.2.25 on 2025-02-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250131_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrel',
            name='weight',
        ),
    ]
